#!/bin/sh

deactivate () {
    # reset old environment variables
    if [ -n "${_OLD_VIRTUAL_PATH:-}" ] ; then
        PATH="${_OLD_VIRTUAL_PATH:-}"
        export PATH
        unset _OLD_VIRTUAL_PATH
    fi
    if [ -n "${_OLD_DEPOT_PATH:-}" ] ; then
        JULIA_DEPOT_PATH="${_OLD_DEPOT_PATH:-}"
        export JULIA_DEPOT_PATH
        unset _OLD_DEPOT_PATH
    fi
    if [ -n "${_OLD_LOAD_PATH:-}" ] ; then
        JULIA_LOAD_PATH="${_OLD_LOAD_PATH:-}"
        export JULIA_LOAD_PATH
        unset _OLD_LOAD_PATH
    fi
    # This should detect bash and zsh, which have a hash command that must
    # be called to get it to forget past commands.  Without forgetting
    # past commands the $PATH changes we made may not be respected
    if [ -n "${BASH:-}" -o -n "${ZSH_VERSION:-}" ] ; then
        hash -r
    fi

    unset VIRTUAL_ENV
    if [ ! "${1:-}" = "nondestructive" ] ; then
    # Self destruct!
        unset -f deactivate
    fi
}

# unset irrelevant variables
deactivate nondestructive

VIRTUAL_ENV="__VENV_DIR__"
export VIRTUAL_ENV

_OLD_VIRTUAL_PATH="$PATH"
PATH="$VIRTUAL_ENV/bin:$PATH"
export PATH

_OLD_DEPOT_PATH="$JULIA_DEPOT_PATH"
JULIA_DEPOT_PATH="__DEPOT_DIR__"
export JULIA_DEPOT_PATH

_OLD_LOAD_PATH="$JULIA_LOAD_PATH"
JULIA_LOAD_PATH=":"
export JULIA_LOAD_PATH

# This should detect bash and zsh, which have a hash command that must
# be called to get it to forget past commands.  Without forgetting
# past commands the $PATH changes we made may not be respected
if [ -n "${BASH:-}" -o -n "${ZSH_VERSION:-}" ] ; then
    hash -r
fi
